/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imasjava_UALLowLevel */

#ifndef _Included_imasjava_UALLowLevel
#define _Included_imasjava_UALLowLevel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imasjava_UALLowLevel
 * Method:    getDimension
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getDimension
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSPutTimed
 * Signature: (ILjava/lang/String;I[D)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_beginIDSPutTimed
  (JNIEnv *, jclass, jint, jstring, jint, jdoubleArray);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSPutTimed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSPutTimed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSPut
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_beginIDSPut
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSPut
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSPut
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSPutNonTimed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_beginIDSPutNonTimed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSPutNonTimed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSPutNonTimed
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSPutSlice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_beginIDSPutSlice
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSPutSlice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSPutSlice
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSReplaceLastSlice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_beginIDSReplaceLastSlice
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSReplaceLastSlice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSReplaceLastSlice
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSGet
 * Signature: (ILjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_beginIDSGet
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSGet
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSGet
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginIDSGetSlice
 * Signature: (ILjava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_imasjava_UALLowLevel_beginIDSGetSlice
  (JNIEnv *, jclass, jint, jstring, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    endIDSGetSlice
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_endIDSGetSlice
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putString
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putString
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putInt
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putBoolean
 * Signature: (ILjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putBoolean
  (JNIEnv *, jclass, jint, jstring, jstring, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putFloat
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DInt
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DBoolean
 * Signature: (ILjava/lang/String;Ljava/lang/String;[ZIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DBoolean
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jbooleanArray, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DString
 * Signature: (ILjava/lang/String;Ljava/lang/String;[Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DString
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jobjectArray, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DFloat
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DInt
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DFloat
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DInt
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DFloat
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect4DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect4DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect5DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect5DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect6DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect6DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect7DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect7DDouble
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastStringSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastStringSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastBooleanSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastBooleanSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jboolean);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jfloat);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect1DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect1DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect1DBooleanSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[ZI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect1DBooleanSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jbooleanArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect1DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect1DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jfloatArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect1DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect1DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect2DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[III)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect2DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect2DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect2DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jfloatArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect2DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect2DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect3DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect3DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect3DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect3DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jfloatArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect3DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect3DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect4DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect4DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect5DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect5DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastVect6DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastVect6DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putStringSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putStringSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putBooleanSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;ZD)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putBooleanSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jboolean, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;FD)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloat, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DD)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DBooleanSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[ZID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DBooleanSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jbooleanArray, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[IIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jintArray, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[FIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jfloatArray, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect4DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect4DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect5DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect5DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect6DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect6DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect7DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DIIIIIIID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect7DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdoubleArray, jint, jint, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    deleteData
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_deleteData
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getString
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imasjava_UALLowLevel_getString
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getInt
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getBoolean
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_imasjava_UALLowLevel_getBoolean
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_imasjava_UALLowLevel_getFloat
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_imasjava_UALLowLevel_getDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DInt
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DString
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DString;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DString
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DBoolean
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DBoolean;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DBoolean
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DFloat
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect1DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect2DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DInt
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect2DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DFloat
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect2DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DInt
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect3DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DInt
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DFloat
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect3DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DFloat
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect3DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect4DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect4DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect4DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect5DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect5DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect5DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect6DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect6DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect6DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect7DDouble
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Limasjava/Vect7DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect7DDouble
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getStringSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imasjava_UALLowLevel_getStringSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getBooleanSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Z
 */
JNIEXPORT jboolean JNICALL Java_imasjava_UALLowLevel_getBooleanSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)F
 */
JNIEXPORT jfloat JNICALL Java_imasjava_UALLowLevel_getFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)D
 */
JNIEXPORT jdouble JNICALL Java_imasjava_UALLowLevel_getDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect1DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect1DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect1DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DIntSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect2DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DIntSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DFloatSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect2DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DFloatSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect2DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect3DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect4DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect4DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect4DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect5DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect5DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect5DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect6DDoubleSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)Limasjava/Vect6DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect6DDoubleSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getUniqueRun
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getUniqueRun
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putCpoDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;IILjava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putCpoDb
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring, jint, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    openDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_openDb
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    createNewRunDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_createNewRunDb
  (JNIEnv *, jclass, jstring, jstring, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    createNewRunParentDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_createNewRunParentDb
  (JNIEnv *, jclass, jstring, jstring, jint, jstring, jstring, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    createSpecifiedRunDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_createSpecifiedRunDb
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    createSpecifiedRunParentDb
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_createSpecifiedRunParentDb
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring, jstring, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getShot
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getShot
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getRun
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getRun
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    beginObject
 * Signature: (IIILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_beginObject
  (JNIEnv *, jclass, jint, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    releaseObject
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_releaseObject
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putObject
 * Signature: (ILjava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putObject
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putStringInObject
 * Signature: (IILjava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putStringInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jstring);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putIntInObject
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putIntInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putFloatInObject
 * Signature: (IILjava/lang/String;IF)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putFloatInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jfloat);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putDoubleInObject
 * Signature: (IILjava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DIntInObject
 * Signature: (IILjava/lang/String;I[II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DIntInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jintArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DStringInObject
 * Signature: (IILjava/lang/String;I[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DStringInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jobjectArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DFloatInObject
 * Signature: (IILjava/lang/String;I[FI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DFloatInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jfloatArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect1DDoubleInObject
 * Signature: (IILjava/lang/String;I[DI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect1DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DIntInObject
 * Signature: (IILjava/lang/String;I[III)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DIntInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jintArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DFloatInObject
 * Signature: (IILjava/lang/String;I[FII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DFloatInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jfloatArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect2DDoubleInObject
 * Signature: (IILjava/lang/String;I[DII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect2DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DIntInObject
 * Signature: (IILjava/lang/String;I[IIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DIntInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jintArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DFloatInObject
 * Signature: (IILjava/lang/String;I[FIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DFloatInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jfloatArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect3DDoubleInObject
 * Signature: (IILjava/lang/String;I[DIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect3DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect4DDoubleInObject
 * Signature: (IILjava/lang/String;I[DIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect4DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect5DDoubleInObject
 * Signature: (IILjava/lang/String;I[DIIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect5DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect6DDoubleInObject
 * Signature: (IILjava/lang/String;I[DIIIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect6DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putVect7DDoubleInObject
 * Signature: (IILjava/lang/String;I[DIIIIIII)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putVect7DDoubleInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jdoubleArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putObjectInObject
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putObjectInObject
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getObjectDim
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getObjectDim
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getObject
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getObject
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getStringFromObject
 * Signature: (IILjava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imasjava_UALLowLevel_getStringFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getIntFromObject
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getIntFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getFloatFromObject
 * Signature: (IILjava/lang/String;I)F
 */
JNIEXPORT jfloat JNICALL Java_imasjava_UALLowLevel_getFloatFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getDoubleFromObject
 * Signature: (IILjava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_imasjava_UALLowLevel_getDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DIntFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect1DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DIntFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DStringFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect1DString;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DStringFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DFloatFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect1DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DFloatFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect1DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect1DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect1DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DIntFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect2DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DIntFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DFloatFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect2DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DFloatFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect2DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect2DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect2DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DIntFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect3DInt;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DIntFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DFloatFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect3DFloat;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DFloatFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect3DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect3DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect3DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect4DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect4DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect4DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect5DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect5DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect5DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect6DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect6DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect6DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getVect7DDoubleFromObject
 * Signature: (IILjava/lang/String;I)Limasjava/Vect7DDouble;
 */
JNIEXPORT jobject JNICALL Java_imasjava_UALLowLevel_getVect7DDoubleFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getObjectFromObject
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getObjectFromObject
  (JNIEnv *, jclass, jint, jint, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    getObjectSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_imasjava_UALLowLevel_getObjectSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdouble);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    putObjectSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;DI)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_putObjectSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jdouble, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    replaceLastObjectSlice
 * Signature: (ILjava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_replaceLastObjectSlice
  (JNIEnv *, jclass, jint, jstring, jstring, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    ualCopyCpo
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_ualCopyCpo
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

/*
 * Class:     imasjava_UALLowLevel
 * Method:    ualCopyCpoEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_UALLowLevel_ualCopyCpoEnv
  (JNIEnv *, jclass, jstring, jstring, jstring, jint, jint, jint, jstring, jstring, jstring, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
