/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imasjava_imas */

#ifndef _Included_imasjava_imas
#define _Included_imasjava_imas
#ifdef __cplusplus
extern "C" {
#endif
#undef imasjava_imas_EMPTY_INT
#define imasjava_imas_EMPTY_INT -999999999L
#undef imasjava_imas_EMPTY_DOUBLE
#define imasjava_imas_EMPTY_DOUBLE -9.0E40
#undef imasjava_imas_INTERPOLATION
#define imasjava_imas_INTERPOLATION 3L
#undef imasjava_imas_CLOSEST_SAMPLE
#define imasjava_imas_CLOSEST_SAMPLE 1L
#undef imasjava_imas_PREVIOUS_SAMPLE
#define imasjava_imas_PREVIOUS_SAMPLE 2L
#undef imasjava_imas_NON_TIMED
#define imasjava_imas_NON_TIMED 0L
#undef imasjava_imas_TIMED
#define imasjava_imas_TIMED 1L
#undef imasjava_imas_TIMED_CLEAR
#define imasjava_imas_TIMED_CLEAR 2L
/*
 * Class:     imasjava_imas
 * Method:    enableMemCache
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_enableMemCache
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_imas
 * Method:    disableMemCache
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_disableMemCache
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_imas
 * Method:    discardAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_discardAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_imas
 * Method:    flushAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_flushAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_imas
 * Method:    discard
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_discard
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_imas
 * Method:    flush
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_flush
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_imas
 * Method:    open
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     imasjava_imas
 * Method:    create
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_create
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     imasjava_imas
 * Method:    openEnv
 * Signature: (Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_openEnv
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_imas
 * Method:    createEnv
 * Signature: (Ljava/lang/String;IIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_createEnv
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_imas
 * Method:    openHdf5
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_openHdf5
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     imasjava_imas
 * Method:    createHdf5
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_createHdf5
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     imasjava_imas
 * Method:    connect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_connect
  (JNIEnv *, jclass, jstring);

/*
 * Class:     imasjava_imas
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_imasjava_imas_disconnect
  (JNIEnv *, jclass);

/*
 * Class:     imasjava_imas
 * Method:    exec
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_imasjava_imas_exec
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     imasjava_imas
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_imas_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
