/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imasjava_wrapper_LowLevel */

#ifndef _Included_imasjava_wrapper_LowLevel
#define _Included_imasjava_wrapper_LowLevel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_print_context
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1print_1context
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_pulse_action
 * Signature: (IIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1pulse_1action
  (JNIEnv *, jclass, jint, jint, jint, jstring, jstring, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_open_pulse
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1open_1pulse
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_close_pulse
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1close_1pulse
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_global_action
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1global_1action
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_slice_action
 * Signature: (ILjava/lang/String;IDI)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1slice_1action
  (JNIEnv *, jclass, jint, jstring, jint, jdouble, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_end_action
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1end_1action
  (JNIEnv *, jclass, jint);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_int
 * Signature: (ILjava/lang/String;Ljava/lang/String;[III[I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1int
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_double
 * Signature: (ILjava/lang/String;Ljava/lang/String;[DII[I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1double
  (JNIEnv *, jclass, jint, jstring, jstring, jdoubleArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_write_data_char
 * Signature: (ILjava/lang/String;Ljava/lang/String;[BII[I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1write_1data_1char
  (JNIEnv *, jclass, jint, jstring, jstring, jbyteArray, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_int
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1int
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_double
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1double
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_read_data_char
 * Signature: (ILjava/lang/String;Ljava/lang/String;II[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_imasjava_wrapper_LowLevel_ual_1read_1data_1char
  (JNIEnv *, jclass, jint, jstring, jstring, jint, jint, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_delete_data
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1delete_1data
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_begin_arraystruct_action
 * Signature: (ILjava/lang/String;Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1begin_1arraystruct_1action
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray);

/*
 * Class:     imasjava_wrapper_LowLevel
 * Method:    ual_iterate_over_arraystruct
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_imasjava_wrapper_LowLevel_ual_1iterate_1over_1arraystruct
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
