include ../../Makefile.common

ifeq (,$(wildcard $(UAL)))
$(error $$UAL is unset)
endif

ifneq (${DEBUG},yes)
OPTFLAG=-O3
else
OPTFLAG=-O0
endif

LD=$(CXX)
CFLAGS=-std=c11 -pedantic -Wall -fPIC ${OPTFLAG} ${DBGFLAGS}
CXXFLAGS=-std=c++11 -pedantic -fPIC -Wall ${OPTFLAG} ${DBGFLAGS}
LDFLAGS=-pthread ${DBGFLAGS}

INCDIR= -I$(UAL)/lowlevel
LIBS= -L$(UAL)/lowlevel
LIBS+= -lal

ifneq ("no","$(strip $(IMAS_MDSPLUS))")
LIBS+= -L$(MDSPLUS_DIR)/lib
LIBS+= -lTreeShr -lTdiShr -lMdsShr -lMdsIpShr -lXTreeShr
endif

ifneq ("no","$(strip $(IMAS_UDA))")
LIBS+= -L$(UDA_HOME)/lib
LIBS+= `pkg-config --libs uda-cpp`
LIBS+= -lssl -lcrypto
endif

ifneq ("no","$(strip $(IMAS_HDF5))")
LIBS+= -L$(HDF5_HOME)/lib
LIBS+= -lhdf5 -ldl -lz
endif

BINOUT=testlowlevel
BINOUT_C=testlowlevel_c
