#cython: language_level=3

from .al_defs cimport *

MAXDIM = AL_MAXDIM

OP_INTERP_0 = AL_OP_INTERP_0
BACKEND_ID_0 = AL_BACKEND_ID_0
OP_RANGE_0 = AL_OP_RANGE_0
OP_ACCESS_0 = AL_OP_ACCESS_0
ACCESS_PULSE_0 = AL_ACCESS_PULSE_0
DATA_TYPE_0 = AL_DATA_TYPE_0
SERIALIZER_PROTOCOL_0 = AL_SERIALIZER_PROTOCOL_0
ERR_0 = AL_ERR_0

GLOBAL_OP = AL_GLOBAL_OP
SLICE_OP = AL_SLICE_OP

READ_OP = AL_READ_OP
WRITE_OP = AL_WRITE_OP
REPLACE_OP = AL_REPLACE_OP

UNDEFINED_INTERP = AL_UNDEFINED_INTERP
CLOSEST_INTERP = AL_CLOSEST_INTERP
PREVIOUS_INTERP = AL_PREVIOUS_INTERP
LINEAR_INTERP = AL_LINEAR_INTERP

UNDEFINED_TIME = AL_UNDEFINED_TIME

OPEN_PULSE = AL_OPEN_PULSE
FORCE_OPEN_PULSE = AL_FORCE_OPEN_PULSE
CREATE_PULSE = AL_CREATE_PULSE
FORCE_CREATE_PULSE = AL_FORCE_CREATE_PULSE
CLOSE_PULSE = AL_CLOSE_PULSE
ERASE_PULSE = AL_ERASE_PULSE

CHAR_DATA = AL_CHAR_DATA
INTEGER_DATA = AL_INTEGER_DATA
DOUBLE_DATA = AL_DOUBLE_DATA
COMPLEX_DATA = AL_COMPLEX_DATA

ASCII_SERIALIZER_PROTOCOL = AL_ASCII_SERIALIZER_PROTOCOL
DEFAULT_SERIALIZER_PROTOCOL = AL_DEFAULT_SERIALIZER_PROTOCOL

UNKNOWN_ERR = AL_UNKNOWN_ERR
CONTEXT_ERR = AL_CONTEXT_ERR
BACKEND_ERR = AL_BACKEND_ERR
LOWLEVEL_ERR = AL_LOWLEVEL_ERR

NO_BACKEND = AL_NO_BACKEND
ASCII_BACKEND = AL_ASCII_BACKEND
MDSPLUS_BACKEND = AL_MDSPLUS_BACKEND
HDF5_BACKEND = AL_HDF5_BACKEND
MEMORY_BACKEND = AL_MEMORY_BACKEND
UDA_BACKEND = AL_UDA_BACKEND

MAX_ERR_MSG_LEN = AL_MAX_ERR_MSG_LEN

AL_VERSION = AL_AL_VERSION
DD_VERSION = AL_DD_VERSION
